version: "3"

services:
  fdk-admin-gui:
    build: ../fdk-admin-gui
    image: dcatno/fdk-admin-gui:latest
    ports:
      - 8136:8000
    environment:
      - OIDC_ISSUER
      - FDK_HARVEST_ADMIN_HOST
      - ORGANISATION_CATALOGUE_HOST
