version: "3"

services:
  fdk-admin-gui:
    build: ../fdk-admin-gui
    image: dcatno/fdk-admin-gui:latest
    ports:
      - 8136:8000
    environment:
      - OIDC_ISSUER=http://localhost:8084/auth/realms/fdk
      - OIDC_CLIENT_ID=fdk-admin-gui
      - FDK_HARVEST_ADMIN_HOST=http://localhost:8134
